name: polla_mundial_2026
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.8.0
  go_router: ^14.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  color: "#0B3D91"
  image: assets/images/logo_splash.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#0B3D91"
    image: assets/images/logo_splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#0B3D91"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/