class FlagHelper {
  static String getFlagEmoji(String teamName) {
    const flags = {
      'México': '🇲🇽',
      'Sudáfrica': '🇿🇦',
      'Rep. de Corea': '🇰🇷',
      'Checa': '🇨🇿',
      'Canadá': '🇨🇦',
      'Bosnia/Herzeg.': '🇧🇦',
      'EE.UU.': '🇺🇸',
      'Paraguay': '🇵🇾',
      'Qatar': '🇶🇦',
      'Suiza': '🇨🇭',
      'Brasil': '🇧🇷',
      'Marruecos': '🇲🇦',
      'Haiti': '🇭🇹',
      'Escocia': '🏴',
      'Australia': '🇦🇺',
      'Turquía': '🇹🇷',
      'Alemania': '🇩🇪',
      'Curazao': '🇨🇼',
      'Países Bajos': '🇳🇱',
      'Japón': '🇯🇵',
      'Costa de Marfil': '🇨🇮',
      'Ecuador': '🇪🇨',
      'Suecia': '🇸🇪',
      'Túnez': '🇹🇳',
      'España': '🇪🇸',
      'Cabo Verde': '🇨🇻',
      'Bélgica': '🇧🇪',
      'Egipto': '🇪🇬',
      'Arabia Saudita': '🇸🇦',
      'Uruguay': '🇺🇾',
      'IR Irán': '🇮🇷',
      'Nueva Zelanda': '🇳🇿',
      'Francia': '🇫🇷',
      'Senegal': '🇸🇳',
      'Iraq': '🇮🇶',
      'Noruega': '🇳🇴',
      'Argentina': '🇦🇷',
      'Argelia': '🇩🇿',
      'Austria': '🇦🇹',
      'Jordán': '🇯🇴',
      'Portugal': '🇵🇹',
      'RD Congo': '🇨🇩',
      'Inglaterra': '🇬🇧',
      'Croacia': '🇭🇷',
      'Ghana': '🇬🇭',
      'Panamá': '🇵🇦',
      'Uzbekistán': '🇺🇿',
      'Colombia': '🇨🇴',
    };

    return flags[teamName] ?? '🏳️';
  }
}